
name: make github pages

on: workflow_dispatch

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Install Gradle (latest version)
        uses: gradle/wrapper-validation-action@v1
        with:
          gradle-version: 'latest'

      - name: Install dependencies
        run: |
          pip install sphinx furo myst_parser sphinx_inline_tabs

      - name: Sphinx build
        run: |
          sphinx-build -M html ./pages/source docs

    # builds docs but ignores compilation step
      - name: Java Docs build
        run: |
          ./gradlew javadoc -x compileJava 

    # Upload built documentation as an artifact for deployment
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: docs/html
    
  deploy:
    needs: build-docs
    runs-on: ubuntu-latest
    permissions:
      pages: write   # Required for GitHub Pages deployment
      id-token: write # Required for OIDC authentication

    steps:
      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2