
name: make github pages

on: workflow_dispatch

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5

      - name: Install dependencies
        run: |
          pip install sphinx furo myst_parser sphinx_inline_tabs

      - name: Sphinx build
        run: |
          sphinx-build -M html ./pages/source docs
    #   - name: Deploy to GitHub Pages
    #     uses: peaceiris/actions-gh-pages@v3
    #     if: ${{ github.ref == 'refs/heads/main' }}
    #     with:
    #       publish_branch: gh-pages
    #       github_token: ${{ secrets.GITHUB_TOKEN }}
    #       publish_dir: docs/html
    #       force_orphan: true

    # Upload built documentation as an artifact for deployment
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: docs/html
    
  deploy:
    needs: build-docs
    runs-on: ubuntu-latest
    permissions:
      pages: write   # Required for GitHub Pages deployment
      id-token: write # Required for OIDC authentication

    steps:
      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2