
name: publish-pages

on: workflow_dispatch

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Empty
        run: 